apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: vjie1uxjl-nodejs 
  janus-idp.io/tekton: vjie1uxjl-nodejs
  backstage.io/kubernetes-id: vjie1uxjl-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: vjie1uxjl-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  